### ISSUE TITLE
how can i visualize the environment while training the agent?

### ISSUE THREAD

**Issue by weixiang-95** [nicrusso7/rex-gym#1]

**Comment by nicrusso7** [comment]
There is no a clean way to do that, as the repo is very work in progress and actually designed for batch training (to run multiple agents). Anyway, you can manually edit this line 

https://github.com/nicrusso7/rex-gym/blob/a10d2669ab69e8b625cc43f1c5813cbe904f11be/envs/gym/rex_gym_env.py#L172

Set this variable to True and you will see the render!

**Comment by nicrusso7** [comment]
Hi @weixiang-95, the latest release contains a new script to visualize the training session (`training_player`). Please feel free to re-open this issue if it raises any issue! :)
