### ISSUE TITLE
how to learn a policy from scratch

### ISSUE THREAD

**Issue by sunwenkai123** [nicrusso7/rex-gym#15]
I want to train the robot to learn to walk from scratch, but I don't know what command or step to achieve it
Kindly let me know what to do.

**Comment by sunwenkai123** [comment]
> I want to train the robot to learn to walk from scratch, but I don't know what command or step to achieve it
> Kindly let me know what to do.

**Comment by IverYangg** [comment]
I am curious too, Do you figure out?
