### ISSUE TITLE
General questions

### ISSUE THREAD

**Issue by darshisen** [nicrusso7/rex-gym#17]
Just a few general questions:

1. How do I run a policy from a trained model?
2. How do I restart training from the same place I left off if I stop in the middle or the training crashes?
3.

**Comment by nicrusso7** [comment]
Hi, thank you for you interest in this project. For general questions/discussions there is a more appropriate `Discussions` panel [here](https://github.com/nicrusso7/rex-gym/discussions).

Regarding your questions:
1. If you mean how to run a policy in a simulation, check out the `policy` [command](https://github.com/nicrusso7/rex-gym#policy-player-run-a-pre-trained-agent). With this command you can run any policy under the policies folder. If you want to run your own policy, just edit this [map](https://github.com/nicrusso7/rex-gym/blob/82dea26bcd8896da06240bcc3abd4de5b4696430/rex_gym/util/flag_mapper.py#L1-L10). Be sure that your policy match the environment (map key), e.g. if you trained a new policy for the `walk` env and you are using the `open_loop` controller, then you need to edit the value of `walk_ol`.

2. Unfortunately this feature is not supported. Any PR is welcome!

Please feel free to open a new discussion if needed!
