### ISSUE TITLE
Offscreen rendering made terrain disappear

### ISSUE THREAD

**Issue by Dzhange** [nicrusso7/rex-gym#19]
HI

I'm trying to add visual signal of the terrain to the agent. 

While rendering in offscreen mode(I turned `render` option to False when initializing environment), I found that the terrain becam invisible, but the robot looks fine. Do you have any idea about how could I render the terrain without GUI? 
![image](https://user-images.githubusercontent.com/35654021/118168995-0727bb00-b45b-11eb-959e-c76f92634b8b.png)

Thanks!

**Comment by nicrusso7** [comment]
Hi, 
you can toggle the pybullet gui pressing 'g'. Check this out for shortcuts: https://pybullet.org/Bullet/phpBB3/viewtopic.php?t=13176 

Let me know if this work for you.

Thanks!

**Comment by Dzhange** [comment]
> Hi,
> you can toggle the pybullet gui pressing 'g'. Check this out for shortcuts: https://pybullet.org/Bullet/phpBB3/viewtopic.php?t=13176
> 
> Let me know if this work for you.
> 
> Thanks!

Sorry I didn't make it clear, in fact I'm running Rex on *a headless server*, so I couldn't visiualize through the GUI, and I initialized the rex-gym environment with `env = config.env(render=False, **self.args)`, and tried to get camera image during simulation. In the end I got the image shown above, where the rex robot is visible but the terrain(I set it to`mounts`) disappeared. I'm wondering how could I render the terrain in that case

Thanks!

**Comment by nicrusso7** [comment]
Now I see what you meant, thanks. So the terrain is created [here](https://github.com/nicrusso7/rex-gym/blob/26663048bd3c3da307714da4458b1a2a9dc81824/rex_gym/envs/rex_gym_env.py#L276) and I can't see why it is actually "invisible" when you run it in headless mode. Did you tried any other terrain? e.g. random. I suspect there is a graphical  issue going on

**Comment by Dzhange** [comment]
Yeah I tried all terrains but none of them was rendered. If you would like to reproduce the problem, just call the `render` function somewhere and store the returned img.

**Comment by Dzhange** [comment]
I also tried to render without GUI on a machine with monitor, and the terrain is still not showing :( .

**Comment by Dzhange** [comment]
Somehow got it working:

1. I upgraded pybullet to newest version
2. changed the render in `getCameraImage` to `ER_TINY_RENDERER`

![image](https://user-images.githubusercontent.com/35654021/118584302-43477c80-b7c9-11eb-9be7-d93604092fd2.png)

**Comment by nicrusso7** [comment]
Awesome! thanks for pointing this out.
