### ISSUE TITLE
Performance issue in the definition of append, rex_gym/agents/ppo/memory.py

### ISSUE THREAD

**Issue by DLPerf** [nicrusso7/rex-gym#25]
Hello, I found a performance issue in the definition of `append`, rex_gym/agents/ppo/memory.py, [tf.stack and tf.gather](https://github.com/nicrusso7/rex-gym/blob/26663048bd3c3da307714da4458b1a2a9dc81824/rex_gym/agents/ppo/memory.py#L77) will be calculated repeatedly during program execution, resulting in reduced efficiency. I think it should be created before the loop(with) in `append`.

Looking forward to your reply. Btw, I am very glad to create a PR to fix it if you are too busy.

**Comment by DLPerf** [comment]
@nicrusso7 Hi, my friend, could you consider my issue asap?

**Comment by nicrusso7** [comment]
Hi, the PPO code was originally forked from the pyBullet repo (https://github.com/bulletphysics/bullet3/tree/master/examples/pybullet/gym/pybullet_envs/minitaur/agents/ppo). More than happy to merge a PR that improves the performance :)

**Comment by nicrusso7** [comment]
Following the PR thread.
