### ISSUE TITLE
Installation error

### ISSUE THREAD

**Issue by RobertSWagoner** [nicrusso7/rex-gym#3]
firstly, well done on what I have read so far. I am trying to install and followed your instructions, however I received an error:
pip install rex_gym
Collecting rex_gym
  Using cached https://files.pythonhosted.org/packages/98/1c/6d979037d598d3ddd410908eba0bbcf76b464ebd22143a8d9682c3a9af26/rex_gym-0.1.7.tar.gz
    ERROR: Command errored out with exit status 1:
     command: 'C:\Users\user\.conda\envs\rex\python.exe' -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-jqupm9ki\\rex-gym\\setup.py'"'"'; __file__='"'"'C:\\Users\\user\\AppData\\Local\\Temp\\pip-install-jqupm9ki\\rex-gym\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base 'C:\Users\user\AppData\Local\Temp\pip-install-jqupm9ki\rex-gym\pip-egg-info'
         cwd: C:\Users\user\AppData\Local\Temp\pip-install-jqupm9ki\rex-gym\
    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\user\AppData\Local\Temp\pip-install-jqupm9ki\rex-gym\setup.py", line 37, in <module>
        '': [f for f in copy_assets('policies')] + [a for a in copy_assets('util')]
      File "C:\Users\user\AppData\Local\Temp\pip-install-jqupm9ki\rex-gym\setup.py", line 37, in <listcomp>
        '': [f for f in copy_assets('policies')] + [a for a in copy_assets('util')]
      File "C:\Users\user\AppData\Local\Temp\pip-install-jqupm9ki\rex-gym\setup.py", line 16, in copy_assets
        yield os.path.join(dirpath.split('/', 1)[1], f)
    IndexError: list index out of range
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

Have you see this error before?  I hope you can help, looking forward to reviewing.

--RW

**Comment by nicrusso7** [comment]
hello! thanks! regarding your issue, are you running it into a python3 virtual environment? looks like you are on Windows, it may be an issue in the setup.py. I'll try to install it on a win machine, thanks for pointing out this!

**Comment by RobertSWagoner** [comment]
Thanks, keep me posted.

--RW

**Comment by RobertSWagoner** [comment]
Yes, I used Anaconda 64bit on Windows 10 Pro following your installation 
steps.

--RW

**Comment by RobertSWagoner** [comment]
Update! I had the opportunity to update my MacBook Pro laptop and then installed Anaconda 64bit and the simulations work.  Let me know what you find on Windows 10 since that would be good as well.

**Comment by nicrusso7** [comment]
Hey @RobertSWagoner, the new version should resolve your issue :) please let me know if this works for you!

**Comment by RobertSWagoner** [comment]
Working good. Thank you.
