### ISSUE TITLE
Training from command line example

### ISSUE THREAD

**Issue by jackwilkinson255** [nicrusso7/rex-gym#9]
Can you give an example of training a policy directly from the command line?

I've tried this but it doesn't seem to produce anything in the logging directory:

rex-gym train --playground True --env walk --log-dir ~/rex-gym/logging

Am I missing some arguments?

**Comment by nicrusso7** [comment]
The agent will save a checkpoint every 500000 steps in the default configuration.

By the way, the `playground` flag is used to spin up a rendered single agent training session. You may want to run a batch session removing it (this will speed up the training).

**Comment by nicrusso7** [comment]
Please feel free to reopen this issue if you incur in any other problem.
